swagger: "2.0"
info:
  version: "0.0.1"
  title: hiring-company-data-api
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /company:
    x-swagger-router-controller: company
    post:
      operationId: insertOne
      description: add a company
      parameters: 
        - name: body
          in: body
          description: company data
          schema: 
            $ref: "#/definitions/Company"
      responses:
        "200": 
          description: Success
          schema: 
            $ref: "#/definitions/CompanyResponse"
        default: 
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /company/filter:
    x-swagger-router-controller: company
    post:
      operationId: find
      description: get a list of company data
      parameters: 
        - name: body
          in: body
          description: filter
          schema:
            $ref: "#/definitions/Filter"
          
      responses: 
        "200": 
          description: Success
          schema: 
            $ref: "#/definitions/CompanyList"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /company/{_id}:
    x-swagger-router-controller: company
    get:
      operationId: findOneById
      description: return a company data by id
      parameters:
        - name: _id
          in: path
          description: company id
          required: true
          type: string
      responses:
        "200": 
          description: Success
          schema:
            $ref: "#/definitions/CompanyResponse"
        default: 
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
    put:
      operationId: updateOneById
      description: update a company data by id
      parameters: 
        - $ref: "#/parameters/_id"
        - name: body
          in: body
          description: data to update
          required: true
          schema:
            $ref: "#/definitions/Company"
      responses: 
        "200": 
          description: Success
          schema: 
            $ref: "#/definitions/CompanyResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    delete:
      operationId: deleteOneById
      description: delete a company data by id
      parameters:
        - $ref: "#/parameters/_id"
      responses:
        "200": 
          description: Success
          schema:
            $ref: "#/definitions/Company"
  /company/{_id}/tag:
    x-swagger-router-controller: tag
    post:
      operationId: createTag
      description: add a tag
      parameters: 
        - $ref: "#/parameters/_id"
        - name: body
          in: body
          description: tag name
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                  
      responses: 
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Tag"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      operationId: findTags
      description: get a tag list from a company
      parameters:
        - $ref: "#/parameters/_id"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/TagList"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /company/{_id}/tag/{tag_id}:
    x-swagger-router-controller: tag
    delete:
      operationId: removeOneTag
      description: remove a tag from a company
      parameters:
        - $ref: "#/parameters/_id"
        - $ref: "#/parameters/tag_id"
      responses:
        "200": 
          description: Success
          schema:
            $ref: "#/definitions/Company"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /company/tag:
    x-swagger-router-controller: tag
    get:
      operationId: findAllTags
      description: list all tags
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/TagList"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /company/tag/{tag_id}:
    x-swagger-router-controller: tag
    get:
      operationId: findCompaniesByTag
      description: get a list of company by tag
      parameters:
        - $ref: "#/parameters/tag_id"
        - name: begin
          in: query
          description: The minimum index of query
          type: integer
          default: 0
        - name: end
          in: query
          description: The maximum index of query
          type: integer
          default: 0
      responses:
        "200": 
          description: Success
          schema:
            $ref: "#/definitions/CompanyList"
        default: 
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /tag/{tag_id}:
    x-swagger-router-controller: tag
    get:
      operationId: findTagById
      description: get a tag by id
      parameters: 
        - $ref: "#/parameters/tag_id"
      responses:
        "200":
          description: Success
          schema: 
            $ref: "#/definitions/Tag"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /company/area:
    x-swagger-router-controller: area
    get:
      operationId: findArea
      description: get all area data
      responses:
        "200":
          description: Success
          schema: 
            $ref: "#/definitions/Area"
        default:
          description: Error
          schema: 
            $ref: "#/definitions/ErrorResponse"
  /company/industry:
    x-swagger-router-controller: industry
    get:
      operationId: findIndustry
      description: get all category data
      responses:
        "200":
          description: Success
          schema: 
            $ref: "#/definitions/Category"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  
  /swagger:
    x-swagger-pipe: swagger_raw
parameters:
  _id:
    name: _id
    in: path
    description: company id
    required: true
    type: string
  tag_id:
    name: tag_id
    in: path
    description: tag id
    required: true
    type: string
# complex objects have schema definitions
definitions:
  Area:
    type: object
  Category:
    type: object
  Filter:
    type: object
    properties:
      queryString:
        description: 關鍵詞
        type: string
      fuzzy: 
        description: 是否自動查詢information, service, welfare, philosophy中有無queryString
        type: boolean
      begin:
        type: integer
        default: 0
      end:
        type: integer
        default: 10
      area:
        type: array
        items:
          type: string
      industry:
        type: array
        items:
          type: string
      employeeLowerBound:
        type: integer
      employeeUpperBound:
        type: integer
      capitalLowerBound:
        type: integer
      capitalUpperBound:
        type: integer
      information:
        type: string
      service:
        type: string
      welfare:
        type: string
      philosophy:
        type: string
      tags:
        type: array
        items:
          type: string
  TagList:
    type: array
    items:
      type: object
      properties: 
        _id:
          type: string
        name: 
          type: string
  Tag: 
    type: object
    description: a tag for some company
    properties:
      name:
        type: string
      companyList:
        type: array
        items:
          type: string
          description: company id
      createTime:
        type: string
      updateTime:
        type: string
  CompanyProfile:
    type: object
    description: 公司介紹
    properties:
      industry:
        description: 產業類別
        type: string
      category:
        description: 產業描述
        type: string
      employee:
        description: 員工人數
        type: integer
      capital:
        description: 資本額
        type: integer
      contact:
        description: 聯絡人
        type: string
      address:
        description: 公司地址
        type: string
      phone:
        description: 公司電話(可能缺項)
        type: string
      fax:
        description: 公司傳真(可能缺項)
        type: string
      website:
        description: 公司網址(可能缺項)
        type: string
      link:
        description: 相關連結(可能缺項)
        type: string
  CompanyList:
    type: array
    items:
      $ref: "#/definitions/Company"
  Company:
    type: object
    properties:
      name: 
        description: 公司名稱
        type: string
      profile:
        $ref: "#/definitions/CompanyProfile"
      information:
        description: 公司簡介
        type: string
      service:
        description: 商品服務
        type: string
      welfare:
        description: 福利制度
        type: string
      philosophy:
        description: 經營理念(可能缺項)
        type: string
      logoUrl:
        description: 公司商標圖
        type: string
      environment:
        type: array
        description: 環境照片(可能缺項)
        items:
          type: object
          properties:
            url: 
              type: string
            description: 
              type: string
      tags:
        type: array
        description: 標籤(內含對應標籤的 ObjectID )
        items:
          type: string
  CompanyResponse:
    type: object
    properties:
      profile:
        $ref: "#/definitions/CompanyProfile"
      information:
        description: 公司簡介
        type: string
      service:
        description: 商品服務
        type: string
      welfare:
        description: 福利制度
        type: string
      philisophy:
        description: 經營理念
        type: string
      createTime:
        description: 新增時間(第一次被放到資料庫的時間)
        type: string
      updateTime:
        description: 更新時間
        type: string
      tags:
        description: 標籤
        type: array
        items:
          type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
